### ISSUE TITLE
bug: sysSelect returns EINTR on Darwin, which should be retried

### ISSUE THREAD

**Issue by justenwalker** [muesli/termenv#12]
I've been trying to use termenv.BackgroundColor() and it seems to work by doing a terminal query. This usually works, except there are some situations where the syscall to read the response returns EINTR. In this case, it falls back to COLORFGBG.
This is fine, except that the data appears to remain on stdout unread, so the query and response gets echo'd to stdout instead.

EINTR is actually a temporary error, and so retrying the read usually succeeds when called again.

This was actually a bug that was fixed in Go itself; so I feel we can take the same approach here:

Issue: https://github.com/golang/go/issues/22838
Relevant Code: https://go-review.googlesource.com/c/go/+/79215/5/src/internal/poll/fd_unix.go

**Comment by muesli** [comment]
Great find!
