### ISSUE TITLE
Fails to build on OpenBSD

### ISSUE THREAD

**Issue by vext01** [muesli/termenv#17]
Hi,

Tried to install the github cli which depends on termenv:
```
$ make
...
# github.com/muesli/termenv
../go/pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:30:12: undefined: termStatusReport
../go/pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:52:12: undefined: termStatusReport
```

**Comment by giordano** [comment]
My understanding is that was fixed by #16, which is in v0.7.1.

Today I'm also experiencing the same issue when building [`cli`](https://github.com/cli/cli) which assumes is what brought also you here.  One of the dependencies of `cli` seems to use `termenv` 0.6, not sure which one yet.

**Comment by muesli** [comment]
I couldn't test termenv with OpenBSD myself, I'm afraid, but I agree that #16 likely fixed this issue. `cli/cli` seems to depend on an older version of `charmbracelet/glamour`, which itself still depends on termenv <0.7.2.

Bumping the `glamour` and/or `termenv` dependency in `cli/cli` probably solves the problem. Try and run this command in your local `cli/cli` checkout:

`go get github.com/charmbracelet/glamour@master`

**Comment by jaywilliams** [comment]
I too was trying to compile the github cli on OpenBSD and came across this same error.

Thanks to a [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248599), I was able to get it to compile by copying the termenv_linux.go file as termenv_openbsd.go. You could also use the symlink method used in the FreeBSD patch, but I didn't try that.

```sh
cd ~/go/pkg/mod/github.com/muesli/termenv@v0.6.0
cp termenv_linux.go termenv_openbsd.go
```

**Comment by muesli** [comment]
That's good to know, thanks for the heads up, @jaywilliams!

**Comment by theStack** [comment]
I also ended up here by trying to compile the _trunk_ branch of the github cli tool on OpenBSD and getting the described error message. With the proposed copy-and-rename-fix of @jaywilliams, everything works fine! Thanks a lot. 🎉

**Comment by muesli** [comment]
Just confirmed on OpenBSD that `termenv` v0.7.2 works fine there. We'll need to bump the `termenv` dependency in `cli` to fix this problem upstream. Closing this here and preparing a PR for `cli`.
