### ISSUE TITLE
Recognize NO_COLOR environment variable

### ISSUE THREAD

**Issue by ungerik** [muesli/termenv#2]
See https://no-color.org/

(would also a way to get your package mentioned on that website)

**Comment by muesli** [comment]
Sounds like a good idea!

**Comment by justenwalker** [comment]
@ungerik what would `NO_COLOR` support mean for this library? I suspect it could be easy to make [termenv.ColorProfile](https://github.com/muesli/termenv/blob/master/termenv.go#L27) to return `NoColor{}` when it is set; but does anything else make sense to change?

**Comment by ungerik** [comment]
I would propose a configuration variable set by querying for the `NO_COLOR` environment variable that disables all coloring functionality of the package, but can be explicitly set to false to disable the default behaviour:

```go
var NoColor = os.Getenv("NO_COLOR") != ""
```

**Comment by justenwalker** [comment]
There is also https://bixense.com/clicolors/ (CLICOLOR/CLICOLOR_FORCE) which could be considered as well; also how do these settings interact? Would CLICOLOR_FORCE=1 override NO_COLOR?

**Comment by ungerik** [comment]
Don't know if CLICOLOR_FORCE should win over NO_COLOR. Maybe just keep is simple on the disable side:

```go
var NoColor = os.Getenv("NO_COLOR") != "" || os.Getenv("CLICOLOR") == "0"
```

**Comment by justenwalker** [comment]
Since `termenv` is a library rather than a CLI itself. I'm personally not a huge fan of having global variables become some library-wide setting; since other libs you import are free to interact with them as well.

Possibly we could implement a function to detect the user's intent and let a consumer of the library choose if they should enable color output.

```golang
// EnvironmentColorProfile returns the color profile based on environment variables set
func EnvironmentColorProfile() Profile {
	if os.Getenv("NO_COLOR") != "" {
		return Ascii
	}
	p := ColorProfile()
	if os.Getenv("CLICOLOR_FORCE") != "0" {
		if p == Ascii {
			return ANSI
		}
		return p
	}
	if os.Getenv("CLI_COLOR") == "0" {
		return Ascii
	}
	return p
}
```

**Comment by justenwalker** [comment]
Added PR #11 to discuss this specific implementation above
