### ISSUE TITLE
error in centos

### ISSUE THREAD

**Issue by crack38** [muesli/termenv#23]
OS Version: CentOS Linux release 7.8.2003 (Core)

Error encountered:
[root@builder airlock-menu]# go get github.com/muesli/termenv
# github.com/muesli/termenv
/root/go_proj/src/src/github.com/muesli/termenv/termenv_unix.go:90:9: readfds.Set undefined (type unix.FdSet has no field or method Set)
/root/go_proj/src/src/github.com/muesli/termenv/termenv_unix.go:107:13: readfds.IsSet undefined (type unix.FdSet has no field or method IsSet)

**Comment by crack38** [comment]
uname -a
Linux builder 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by muesli** [comment]
I assume you have a fairly old Go version. Please update to at least Go 1.12.

**Comment by paramah** [comment]
I have the same error:

```
[paramah@rork test-bubble]$ go get github.com/muesli/termenv
# github.com/muesli/termenv
../github.com/muesli/termenv/termenv_unix.go:90:9: readfds.Set undefined (type unix.FdSet has no field or method Set)
../github.com/muesli/termenv/termenv_unix.go:107:13: readfds.IsSet undefined (type unix.FdSet has no field or method IsSet)
[paramah@rork test-bubble]$ go version
go version go1.15.3 linux/amd64
```

**Comment by muesli** [comment]
"Ancient" kernel as well?

**Comment by camandel** [comment]
I've tried with RHEL 7.6 (kernel 3.10.0-957), Go 1.13 and it works.

**Comment by crack38** [comment]
> 
> 
> I assume you have a fairly old Go version. Please update to at least Go 1.12.

I am using go version go1.13.11 linux/amd64
CentOS Linux release 7.8.2003 (Core)

**Comment by muesli** [comment]
Do you have Go modules enabled? Can you try with:

```bash
GO111MODULE="on" go get github.com/muesli/termenv
```

**Comment by crack38** [comment]
> 
> 
> Do you have Go modules enabled? Can you try with:
> 
> ```shell
> GO111MODULE="on" go get github.com/muesli/termenv
> ```

no output, same error on go build

**Comment by muesli** [comment]
> no output, same error on go build

That would suggest that the `go get` actually succeeded. Try your build with modules enabled, too:

```bash
GO111MODULE="on" go build -v
```

**Comment by crack38** [comment]
this problem went away. probably an environment problem. thanks everyone.

**Comment by muesli** [comment]
Thanks @crack38, closing this one then.
