### ISSUE TITLE
Escape codes printed when using color detection

### ISSUE THREAD

**Issue by grant0417** [muesli/termenv#50]
## Bug

When using termenv's color functions, input to stdin while the color function is running will cause anci escape codes text to be printed. Example of outputted text: `[[24;26R^[[24;35R^[[24;44R^[[24;53R^[[24;62R^`

## Steps to reproduce:

Tested on MacOs and Linux using zsh and bash

1. Run the following go program

```go
func main() {
	for i := 0; i < 100000; i++ {
		termenv.ForegroundColor()
	}
}
```

2. Make any input while it is running

**Comment by muesli** [comment]
Thanks for the report. This should be fixed in master. If you can still reproduce it, please let me know which terminal / platform this was on. Thank you!
