### ISSUE TITLE
A way to force colored output (CLICOLOR_FORCE?)

### ISSUE THREAD

**Issue by orlangure** [muesli/termenv#69]
Hi!

Thank you for working on this library. I recently started using it via bubbletea, and I'm now facing an issue while writing tests for gocovsh.

I'm trying to use `.golden` files to test that the output matches some known template, but the rendered output depends on [`ColorProfile`](https://github.com/muesli/termenv/blob/ce3deab710bac3fcf476909f2ad1d5f6d6d2e37c/termenv.go#L44) return value. When running the test locally using `go test` (without using any package name), the rendered output includes color codes. When running the test in any other way, like `go test .` or `go test ./...` (with package names included), the `os.Stdout` is not a tty, so `ColorProfile` causes the colors to disappear.

I saw that there are [environment variables](https://bixense.com/clicolors/) like `CLICOLOR_FORCE` mentioned in `termenv` code, but even using these variables does not cause the output to be colored.

I'm wondering if it is possible (technically) and not overly complex to allow to force colored output even in cases when `os.Stdout` is not a tty, or anything else is wrong. It would help a lot when writing golden-file based tests that verify CLI tool outputs without having a proper terminal.

If there is a way to achieve that in theory, I'm willing to try and implement this feature.

Thank you!

**Comment by muesli** [comment]
I would suggest testing against a fixed color profile, e.g. `termenv.TrueColor`. Relying on the auto detection is going to be too non-deterministic.

**Comment by orlangure** [comment]
Thank you. As I wrote in the PR, I ended up setting a fixed color profile as you suggested.
