### ISSUE TITLE
Support hyperlinks

### ISSUE THREAD

**Issue by makeworld-the-better-one** [muesli/termenv#71]
Many terminals and CLI tools now support [hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). It would be nice if this could be used in termenv, and later lipgloss.

I was going to make a PR, but I wasn't sure what the best method of doing this would be. It would require some refactoring, as `style.go` only supports CSI commands currently from what I understand. Also I'm not sure what you'd like to do with the id parameter, if it should be able to be set.

I'm not attached to making this PR or anything, so if anyone would like to implement this go right ahead :smile:

**Comment by dekimsey** [comment]
So for what it's worth I was able to do this by re-implmenting Style myself. It's ... kludgy as I'm not a terminal expert. At all.

https://gist.github.com/dekimsey/e0c668d2a543015f9aa3528ceeb4b064

**Comment by muesli** [comment]
There's now support for hyperlinks in v0.13.0: https://github.com/muesli/termenv/blob/master/hyperlink.go
