### ISSUE TITLE
illumos build broken

### ISSUE THREAD

**Issue by teutat3s** [muesli/termenv#72]
Hello
thank you for working on this!

It seems https://github.com/muesli/termenv/commit/5ac8409525e03ee6cd96daeae32d47902b88f32a broke building this on `illumos`. To reproduce (latest `pkgsrc-trunk`, `go117`):
```
go install github.com/minio/mc@latest
...
go/pkg/mod/github.com/muesli/termenv@v0.11.1-0.20220204035834-5ac8409525e0/termenv_unix.go:27:29: multiple-value unix.Getpgrp() in single-value context
```

Sadly I'm not well-versed enough with go's unix std lib to say what special handling illumos would need to fix this.

EDIT:
just to confirm, when downgrading to a commit before this change it builds fine with:
```
git clone https://github.com/minio/mc
cd mc
go get github.com/muesli/termenv@afdc360daa456985264728b9de86992f20965e80
go build .
```

**Comment by muesli** [comment]
Thanks for the heads up! Fixing.

**Comment by teutat3s** [comment]
Wow that was fast, thank you very much!
