### ISSUE TITLE
Plan 9 support

### ISSUE THREAD

**Issue by mrusme** [muesli/termenv#75]
Just tried releasing a small tool that I've built, where a dependency seems to depend on this library, under Plan 9 and got [the following error](https://github.com/mrusme/reader/runs/5261881951?check_suite_focus=true):

```
⨯ release failed after 787.10s error=failed to build for plan9_amd64: exit status 2: # github.com/muesli/termenv
Error: ../../../go/pkg/mod/github.com/muesli/termenv@v0.11.0/termenv.go:49:9: undefined: colorProfile
Error: ../../../go/pkg/mod/github.com/muesli/termenv@v0.11.0/termenv.go:58:9: undefined: foregroundColor
Error: ../../../go/pkg/mod/github.com/muesli/termenv@v0.11.0/termenv.go:67:9: undefined: backgroundColor

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.5.0/x64/goreleaser' failed with exit code 1
```

Would it be possible to make termenv support building on Plan 9?

**Comment by muesli** [comment]
I've added shims for Plan9 that will return default values for `colorProfile`, `foregroundColor`, `backgroundColor`. Happy to accept PRs for proper implementations.
