### ISSUE TITLE
No color with version > 0.9.0

### ISSUE THREAD

**Issue by alswl** [muesli/termenv#98]
After upgrade to 0.12.0, I found my cli is running with no color. After seeking problems, I found termenv' version is the root casue.

Show the code:

```
git clone git@github.com:alswl/bubble-table.git
g rev-parse HEAD
635b501f4a8b900b93291b3841eadabf16d78295
cat go.mod | grep termenv
        github.com/muesli/termenv v0.9.0 // indirect
go mod tidy; go run examples/features/main.go
```

<img width="590" alt="image" src="https://user-images.githubusercontent.com/227562/198184620-30e58ac0-ae03-4dd1-9842-117d11c8f023.png">

After upgrade:

```
gsed -i 's/termenv v0.9.0/termenv v0.10.0/g' go.mod
go mod tidy; go run examples/features/main.go
```

<img width="614" alt="image" src="https://user-images.githubusercontent.com/227562/198184790-3fc0a1d3-cc09-4ede-b07b-e1743442542d.png">

And the latest 0.12.0 still not works for me.

My system versions:

```
➜  bubble-table git:(main) ✗ neofetch
                    'c.          ?
                 ,xNMM.          -------------------------------
               .OMMMMo           OS: macOS 12.6 21G115 arm64
               OMMM0,            Host: MacBookPro18,1
     .;loddo:' loolloddol;.      Kernel: 21.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 3 days, 1 hour, 41 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 502 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1728x1117, 2560x1440
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1 Pro
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1 Pro
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 5563MiB / 32768MiB
       .cooc,.    .,coo:.


```

**Comment by muesli** [comment]
Can you check & share the values of the following environment variables, please:

- TERM
- COLORTERM
- TERM_PROGRAM
- CI
- CLICOLOR
- NO_COLOR

**Comment by muesli** [comment]
Since the `CI` check wasn't in v0.9.0 yet, I'm assuming the `CI` environment variable has some value on your system?

**Comment by alswl** [comment]
@muesli 
The reproduce process between version did not modified any ENV or others settings.

My environments variables:

```
➜  ~ echo $TERM
screen-256color
➜  ~ echo $COLORTERM
truecolor
➜  ~ echo $TERM_PROGRAM
tmux
➜  ~ echo $CI
true
➜  ~ echo $TERM_PROGRAM
tmux
➜  ~ echo $NO_COLOR

```

**Comment by muesli** [comment]
> ➜  ~ echo $CI
> true

Unsetting this variable will enable the colored output again. It's something I had to introduce because some CIs (CircleCI) in particular just time out responding to OSC messages.

**Comment by alswl** [comment]
@muesli Thanks for you reply, it works for me.

It's so weird that I didn't explicitly specify that my environment has this `CI` variable.

**Comment by alswl** [comment]
I found the settings finally.

Another CLI using this variable for indicate upgrade or not.

```
# disable waque auto upgrade
export CI=true
```

**Comment by muesli** [comment]
> ```
> # disable waque auto upgrade
> export CI=true
> ```

That seems rather odd and a bit of a misuse of this particular env var.

You can alternatively enforce colors with the `CLICOLOR_FORCE` env var. In code, you could pass your own environment to termenv or set a fixed profile.

**Comment by alswl** [comment]
@muesli Thanks for your patient guide.
